
import React from "react";
import { Link } from "react-router-dom";

const CaptionsSEO = ({setActiveTab}) => {
  return (
    <main className="min-h-screen flex flex-col items-center justify-start bg-gradient-to-br from-gray-800 via-gray-900 to-black p-6">
      <div className="w-full max-w-4xl space-y-6 bg-gray-850 rounded-3xl shadow-2xl p-8">
        <h1 className="text-4xl font-extrabold text-center text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
          AI Instagram Captions Generator
        </h1>

        <p className="text-gray-300 text-lg">
          Are you struggling to find the perfect Instagram caption? Our AI Instagram Captions Generator helps you craft creative, viral-ready captions for every type of post. Whether it’s a reel, photo, story, or carousel, our AI tool provides captions that engage your audience and increase reach.
        </p>

        <h2 className="text-2xl font-semibold text-gray-200">Why AI Instagram Captions Are Important</h2>
        <p className="text-gray-300">
          Captions are more than just words—they drive engagement, boost discoverability, and make your posts stand out. Using our AI tool, you can:
        </p>
        <ul className="list-disc list-inside text-gray-300 space-y-2">
          <li>Save time creating captions for multiple posts.</li>
          <li>Generate captions tailored to your niche, mood, and location.</li>
          <li>Use trending slang, emojis, and engagement hooks.</li>
          <li>Improve post performance on Instagram Explore and Reels.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-200">How to Use Our AI Instagram Captions Generator</h2>
        <p className="text-gray-300">
          Follow these simple steps to generate high-quality captions:
        </p>
        <ol className="list-decimal list-inside text-gray-300 space-y-2">
          <li>Enter the topic or theme of your post.</li>
          <li>Select the mood or tone of your caption.</li>
          <li>Optionally add your location for personalized captions.</li>
          <li>Click “Generate” to get multiple AI-created captions instantly.</li>
          <li>Copy the caption and use it in your Instagram post.</li>
        </ol>

        <h2 className="text-2xl font-semibold text-gray-200">Examples of Captions Generated by AI</h2>
        <p className="text-gray-300">
          Here are a few examples our AI might generate for a travel post:
        </p>
        <ul className="list-disc list-inside text-gray-300 space-y-2">
          <li>"Chasing sunsets and memories 🌅✨ #TravelVibes"</li>
          <li>"Lost in the beauty of the city streets 🏙️ #UrbanExplorer"</li>
          <li>"Sun, sand, and smiles 🏖️ #BeachLife"</li>
          <li>"Adventure awaits… are you ready? 🌍 #Wanderlust"</li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-200">Tips for Writing Better Instagram Captions</h2>
        <ul className="list-disc list-inside text-gray-300 space-y-2">
          <li>Keep captions short and punchy for Reels.</li>
          <li>Use emojis strategically to convey emotion.</li>
          <li>Include a call-to-action (CTA) like “Tag a friend” or “Double tap if you agree.”</li>
          <li>Mix trending hashtags with niche-specific ones for better reach.</li>
          <li>Experiment with humor, storytelling, and questions to boost engagement.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-200">FAQs About AI Instagram Captions</h2>
        <p className="text-gray-300 font-semibold">Q: Can AI captions really increase engagement?</p>
        <p className="text-gray-300">A: Yes! Captions that are tailored, creative, and trending are more likely to catch attention and drive interactions.</p>

        <p className="text-gray-300 font-semibold">Q: Is the AI generator free?</p>
        <p className="text-gray-300">A: Absolutely! You can generate unlimited captions without any cost.</p>

        <p className="text-gray-300 font-semibold">Q: Can I customize the tone of the captions?</p>
        <p className="text-gray-300">A: Yes, you can set the mood or tone like funny, motivational, romantic, or professional.</p>
  {/* Call to Action */}
        <section className="space-y-4 text-center">
          <p className="text-gray-300">
            Ready to create your perfect Instagram Caption 
             Try our <strong>AI Caption Generator tools</strong> now!
          </p>
          <Link
           state={{tab:"captions"}}
            to="/"
            className="inline-block px-6 py-3 bg-purple-500 hover:bg-purple-600 rounded-lg font-semibold text-white transition"
          >
            Generate Now
          </Link>
        </section>
        <p className="text-gray-300">
          Explore more tools to boost your Instagram presence:{" "}
          <Link to="/bio-seo" className="text-purple-400 underline hover:text-purple-600">Bio Generator</Link> |{" "}
          <Link to="/name-seo" className="text-purple-400 underline hover:text-purple-600">Username Generator</Link> |{" "}
          <Link to="/hashtags-seo" className="text-purple-400 underline hover:text-purple-600">Hashtags Generator</Link>
        </p>
      </div>
    </main>
  );
};

export default CaptionsSEO;
