import React from "react";
import { Link } from "react-router-dom";

const HashtagsSEO = ({setActiveTab}) => {
    return (
        <main className="min-h-screen flex flex-col items-center justify-start bg-gradient-to-br from-gray-800 via-gray-900 to-black p-6">
            <div className="w-full max-w-4xl space-y-6 bg-gray-850 rounded-3xl shadow-2xl p-8">
                <h1 className="text-4xl font-extrabold text-center text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
                    Instagram Hashtags AI Generator
                </h1>

                <p className="text-gray-300 text-lg">
                    Boost your Instagram reach and engagement with our AI-powered Instagram Hashtags Generator. Create trending, niche-specific, and viral hashtags for your posts and reels in seconds. Our AI tool helps you maximize visibility while saving time on research.
                </p>

                <h2 className="text-2xl font-semibold text-gray-200">Why Instagram Hashtags Are Important</h2>
                <p className="text-gray-300">
                    Hashtags increase discoverability, help your content reach the right audience, and can grow your followers faster. Using AI-generated hashtags ensures you get a mix of trending, niche, and broad hashtags that optimize post performance.
                </p>

                <ul className="list-disc list-inside text-gray-300 space-y-2">
                    <li>Save time finding trending hashtags for your niche.</li>
                    <li>Use AI to generate hashtags optimized for engagement and reach.</li>
                    <li>Improve your Instagram Explore and Reels performance.</li>
                    <li>Get hashtags tailored for your location, mood, and topic.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-200">How to Use Our AI Instagram Hashtags Generator</h2>
                <ol className="list-decimal list-inside text-gray-300 space-y-2">
                    <li>Enter the topic or theme of your post or reel.</li>
                    <li>Optionally add a mood or location for customized hashtags.</li>
                    <li>Click “Generate” to receive a list of optimized hashtags instantly.</li>
                    <li>Copy and paste the hashtags into your Instagram post for maximum reach.</li>
                </ol>

                <h2 className="text-2xl font-semibold text-gray-200">Example Hashtags Generated by AI</h2>
                <p className="text-gray-300">
                    For a travel reel, our AI might generate hashtags like:
                </p>
                <ul className="list-disc list-inside text-gray-300 space-y-2">
                    <li>#TravelVibes #Wanderlust #AdventureAwaits</li>
                    <li>#BeachLife #CityExplorer #HiddenGems</li>
                    <li>#TravelGram #InstaTravel #ExploreTheWorld</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-200">Tips for Using Instagram Hashtags Effectively</h2>
                <ul className="list-disc list-inside text-gray-300 space-y-2">
                    <li>Use a combination of trending, niche, and broad hashtags for best results.</li>
                    <li>Limit to 15–20 hashtags per post to avoid spammy appearance.</li>
                    <li>Change hashtags regularly to reach new audiences.</li>
                    <li>Include location-based hashtags for local visibility.</li>
                    <li>Monitor performance and adjust hashtags based on engagement.</li>
                </ul>

                <h2 className="text-2xl font-semibold text-gray-200">FAQs About AI Instagram Hashtags</h2>
                <p className="text-gray-300 font-semibold">Q: How does AI generate hashtags?</p>
                <p className="text-gray-300">A: Our AI analyzes your topic, mood, and location to generate relevant hashtags that match trending patterns on Instagram.</p>

                <p className="text-gray-300 font-semibold">Q: Can AI hashtags increase post reach?</p>
                <p className="text-gray-300">A: Yes! Using well-targeted hashtags increases discoverability and engagement, helping your posts reach the right audience.</p>

                <p className="text-gray-300 font-semibold">Q: Are these hashtags free to use?</p>
                <p className="text-gray-300">A: Absolutely! You can generate unlimited hashtags without any cost.</p>
                {/* Call to Action */}
                <section className="space-y-4 text-center">
                    <p className="text-gray-300">
                        Ready to create your perfect Instagram Hashtags
                        Try our <strong>AI Hastags Generator tools</strong> now!
                    </p>
                    <Link
                    state={{tab:"hashtags"}}
                        to="/"
                        className="inline-block px-6 py-3 bg-purple-500 hover:bg-purple-600 rounded-lg font-semibold text-white transition"
                    >
                        Generate Now
                    </Link>
                </section>
                <p className="text-gray-300">
                    Explore more AI tools for Instagram growth:{" "}
                    <Link to="/captions-seo" className="text-purple-400 underline hover:text-purple-600">Captions Generator</Link> |{" "}
                    <Link to="/bio-seo" className="text-purple-400 underline hover:text-purple-600">Bio Generator</Link> |{" "}
                    <Link to="/name-seo" className="text-purple-400 underline hover:text-purple-600">Username Generator</Link>
                </p>
            </div>
        </main>
    );
};

export default HashtagsSEO;
